version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development

  tests:
    build: .
    command: python manage.py test modules.forms
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=test
